version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
  
  identity_access_mysql:
    image: mysql:8.0
    container_name: identity_access_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network
    ports:
      - "3307:3306"
  
  taskmanage_mysql:
    image: mysql:8.0
    container_name: taskmanage_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel_db_taskmanage
      MYSQL_USER: user2
      MYSQL_PASSWORD: password2
    volumes:
      - dbdata_taskmanage:/var/lib/mysql
    networks:
      - app-network
    ports:
      - "3308:3306"

  identity_access:
    build:
      context: ./identity_access
      dockerfile: Dockerfile
    container_name: identity_access
    volumes:
      - .:/var/www/html
    ports:
      - "8080:80"
    networks:
      - app-network

  task_management:
    build:
      context: ./task_management
      dockerfile: Dockerfile
    container_name: task_management
    volumes:
      - .:/var/www/html
    ports:
      - "8081:80"
    networks:
      - app-network

  ddd_common_lib:
    build:
      context: ./ddd_common_lib
      dockerfile: Dockerfile
    container_name: ddd_common_lib
    volumes:
      - .:/var/www/html

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
  dbdata_taskmanage:
    driver: local
  rabbitmq_data: