@startuml task_management

entity project {
    project_id
    --
    project_name
    project_overview
    project_status
    progress_rate
}

entity project_member {
    project_id(FK)
    user_id
    --
    project_participation_status
    role
}

entity ticket {
    project_id(FK)
    ticket_id
    --
    parent_ticket_id(FK)
    ticket_assignment(FK)
    ticket_name
    ticket_overview
    progress_rate
    status
}

project ||--|{ project_member
project ||--o{ ticket
@enduml