@startuml タスク管理
title タスク管理
left to right direction
actor ホスト
actor メンバー

rectangle {
    ホスト --> (プロジェクトを新規作成する)
    ホスト --> (プロジェクトを削除する)
    ホスト --> (参加プロジェクトを閲覧する)
    ホスト --> (プロジェクトのステータスを更新する)
    (参加プロジェクトを閲覧する) <-- メンバー
}

rectangle {
    ホスト --> (プロジェクトにメンバーを追加する)
    ホスト --> (メンバーを削除する)
    ホスト --> (プロジェクトに参加しているメンバーを閲覧する)
    ホスト --> (プロジェクトに追加するメンバーに招待メールを送信する)
}

rectangle {
    ホスト --> (プロジェクトのタスクを閲覧する)
    ホスト --> (プロジェクトのタスクを作成する)
    ホスト --> (プロジェクトのタスクに子タスクを追加する)
    ホスト --> (プロジェクトのタスクを編集する)
    ホスト --> (プロジェクトのタスクを完了する)
    ホスト --> (プロジェクトのタスクを削除する)
    (プロジェクトのタスクを作成する) <-- メンバー
    (プロジェクトのタスクに子タスクを追加する) <-- メンバー
    (プロジェクトのタスクを編集する) <-- メンバー
    (プロジェクトのタスクを完了する) <-- メンバー
    (プロジェクトのタスクを削除する) <-- メンバー
    (プロジェクトのタスクを閲覧する) <-- メンバー
}
@enduml