@startuml
title グループ管理
left to right direction
actor グループ管理者
actor システム
actor グループの参加者

rectangle {
   グループ管理者 --> (グループ一覧を閲覧する)
   グループ管理者 --> (グループに所属しているメンバーを閲覧する)
   グループ管理者 --> (グループ名を入力して\nグループを新規作成する)
   グループ管理者 --> (グループにユーザーを招待する)
   (招待されたユーザー宛てに招待メールを送信する) <-- システム
   グループ管理者 --> (グループを削除する)
   グループ管理者 --> (グループからユーザーを退出させる)
   グループ管理者 --> (グループに参加するユーザーの\nグループへの参加を了承する)
}

rectangle {
    グループの参加者 --> (グループへの招待を了承する)
    (ユーザーをグループに追加する) <-- システム
    グループの参加者 --> (参加しているグループを閲覧する)
    グループの参加者 --> (参加しているグループのメンバーを閲覧する)
    グループの参加者 --> (グループから退出する)
}
@enduml