@startuml
title ユーザー登録
left to right direction
actor ユーザー
actor システム
rectangle {
   ユーザー --> (メールアドレスとパスワードを入力し\nユーザー仮登録を行う)
   (入力されたメールアドレスに本登録確認メールを送信する) <-- システム
   ユーザー --> (本登録確認メールから本登録を行い\nユーザー登録を完了する)
   ユーザー --> (本登録確認メールの再送を依頼する)
}
@enduml