@startuml チケット集約

title チケット集約

package "チケット集約(ProjectAggregation)" {
    class Ticket << (R,red) RootEntity >> {
       projectId: ProjectId
       ticketId: TicketId
       parentTicketId: ?TicketId
       ticketName: TicketName
       ticketOverview: TicketOverview
       progresRate: TicketProgresRate
       ticketAssignment チケット担当者: UserId
       status: TicketStatus
    }

    class TicketId {
        - value: string
    }

    class TicketName {
        - value: string
    }

    class TicketOverview {
        - value: string
    }

    class TicketProgresRate {
        - value: string
    }

    enum TicketStatus {
        notStarted(未着手)
        ongoing(進行中)
        finished(終了済み)
    }

    note bottom of Ticket
        ・チケット担当者は、プロジェクトメンバーの中から設定できる
        ・チケット担当者は一人のみ設定可能
        ・チケットを作成したら、チケット担当者に通知がいく
        ・チケット担当者は変更できる
        ・チケット担当者が変更されたら、新しいチケット担当者に通知がいく
        ・toDo: チケットにコメントを残せるようにする
    end note

    note bottom of TicketId
        ・年月日時分秒ミリ秒の形式
        ・プロジェクトごとに一意なID
    end note

    note bottom of TicketName
        ・チケット名は、100文字以内
        ・プロジェクト内で一意な名前を設定する
    end note

    note bottom of TicketOverview
        チケットの概要は、500文字以内
    end note

    note bottom of TicketProgresRate
        ・チケットの進捗率は、0〜100の数値
        ・チケット担当者のみが変更できる
        ・todo: チケットの進捗率を更新したらプロジェクトの進捗率も自動で更新できるようにする
    end note

    note bottom of TicketStatus
        ・プロジェクト内の全てのチケットステータスが終了済みの場合、
          プロジェクトのステータスも終了済みになる
        ・ステータスが更新されたらプロジェクトリーダーに通知がいく
    end note

    Ticket -down-> Project.ProjectId
    Ticket *-down- TicketId
    Ticket *-down- TicketName
    Ticket *-down- TicketOverview
    Ticket *-down- TicketProgresRate
    Ticket *-down- TicketStatus
    Ticket -down-> auth.UserId
}