@startuml プロジェクト集約

title プロジェクト集約

package "プロジェクト集約(ProjectAggregation)" {
    class Project << (R,red) RootEntity >> {
       projectId: ProjectId
       projectName: ProjectName
       projectOverview: ProjectOverview
       projectStatus: ProjectStatus
       projectMember: ProjectMember[]
       progresRate: ProjectProgresRate
    }

    class ProjectId {
        - value: string
    }

    class UserEmail {
        - value: string
    }

    class ProjectName {
        - value: string
    }

    class ProjectOverview {
        - value: string
    }

    enum ProjectStatus {
        notStarted(未着手)
        ongoing(進行中)
        finished(終了済み)
    }

    class ProjectMember {
        - userId: UserId
        - projectParticipationStatus: ProjectParticipationStatus
        - projectRole: ProjectRole
    }

    enum ProjectParticipationStatus {
        invited(招待済み)
        participated(参加済み)
    }

    enum ProjectRole {
        leader(リーダー)
        member(メンバー)
    }

    note bottom of ProjectId
        ULIDの形式
    end note

    note bottom of ProjectName
        ・プロジェクト名は、100文字以内
        ・ユーザーが管理しているプロジェクトの中で一意な名前を設定する
        ・プロジェクトリーダーのみが変更できる
    end note

    note bottom of ProjectOverview
        ・プロジェクトの概要は、500文字以内
        ・プロジェクトリーダーのみが変更できる
    end note

    note bottom of ProjectMember
        ・プロジェクトリーダーのみがメンバーを招待できる
        ・プロジェクトリーダーは退会できない
        ・メンバーを招待するとプロジェクト参加ステータスが招待済みになり、招待したメンバーに招待メールが届く
        ・招待されたメンバーは、招待メールに記載されたURLからプロジェクトに参加できる
        ・メンバーがプロジェクトに参加すると、プロジェクト参加ステータスが参加済みになる
        ・メンバーがプロジェクトに参加すると、リーダーにメールが届く
        ・プロジェクトメンバーは退会できる
        ・メンバーが退会すると、リーダーにメールが届く
        ・チケットの担当者に設定されているメンバーは退会不可
    end note

    note bottom of UserId
        identity_accessコンテキストから取得する
    end note

    note bottom of ProjectProgresRate
        ・プロジェクトの進捗率は、0%以上100%以下
        ・toDo: チケットの進捗率と同期させる
    end note

    Project *-down- ProjectId
    Project *-down- ProjectName
    Project *-down- ProjectOverview
    Project *-down- ProjectStatus
    Project "1" *-down- "1..*" ProjectMember
    Project *-down- ProjectProgresRate
    Project -down-> auth.UserId
}

@enduml