@startuml 認証アカウント関連

title 認証アカウント集約

package "認証アカウント集約(Aggregation)" {
    class "AuthenticationAccount\n認証アカウント" as AuthenticationAccount << (R,red) RootEntity >> {
        userId: UserId
        email: Email
        password: Password
        DefinitiveRegistrationCompletedStatus 本登録済みステータス: DefinitiveRegistrationCompletedStatus
        loginRestriction ログイン制限: LoginRestriction
        unsubscribeStatus: 退会済みステータス: UnsubscribeStatus
    }

    class UserId {
        - value: string
    }

    class UserEmail {
        - value: string
    }

    class UserPassword {
        - value: string
    }

    class "DefinitiveRegistrationCompletedStatus\n本登録済みステータス" as DefinitiveRegistrationCompletedStatus {
        + value: Enum { verified(本登録済み), unverified(未登録)}
    }

    class "LoginRestriction\nログイン制限" as LoginRestriction {
        - failedLoginCount ログイン失敗回数: FailedLoginCount
        - loginRestrictionStatus ログイン制限ステータス: LoginRestrictionStatus
        - nextLoginAllowedAt 次回ログイン可能日時: NextLoginAllowedAt
    }

    class "LoginRestrictionStatus\nログイン制限ステータス" as LoginRestrictionStatus {
        + value: Enum { restricted(制限中), unrestricted(制限なし)}
    }

    class "FailedLoginCount\nログイン失敗回数" as FailedLoginCount {
        - value: int
    }

    class "NextLoginAllowedAt\n次回ログイン可能日時" as NextLoginAllowedAt {
        - value: DatetimeImutable
    }

    class "UnsubscribeStatus\n退会済みステータス" as UnsubscribeStatus {
        + value: Enum { Unsubscribe(退会済み), Subscribed(未退会)}
    }

    note bottom of AuthenticationAccount
        ・本登録済みステータスが本登録済みの場合のみ、ログインが行える
        ・退会の場合、ユーザーIDと退会済みステータス以外のデータが削除される
    end note

    note bottom of UserId
        userIdはULIDやUUIDv7などの時系列ソート可能なIDを用いる
    end note

    note bottom of DefinitiveRegistrationCompletedStatus
        本登録確認メールでの確認が済んだら「本登録済み」になる 
    end note

    note bottom of UserPassword
        ・ステータスが「本登録済み」の場合のみパスワードの変更が行える
        ・ログイン制限中はパスワードの変更が行えない
        ・パスワードは8文字以上の文字列
        ・パスワードは大文字、小文字、数字、記号をそれぞれ1文字以上含める必要がある
        ・nextTask: パスワードを変更したときにメールを送信する
    end note

    note bottom of UserEmail
        ・重複したメールアドレスは存在しない
        ・255文字以内
        ・メールアドレスの形式
    end note

    note bottom of FailedLoginCount
        ・0以上10以下の整数
        ・ログインに失敗した回数が10回を超えると、ログイン制限がかかる
    end note

    note bottom of NextLoginAllowedAt
        ・ログイン制限がかかった場合、次回ログイン可能日時が設定される
        ・ログイン制限が解除された場合、次回ログイン可能日時はnullになる
        ・ログイン制限は10分間
    end note

    note bottom of LoginRestrictionStatus
        ・ログイン制限がかかった場合、ログイン制限ステータスが「制限中」になる
        ・ログイン制限が解除された場合、ログイン制限ステータスが「制限なし」になる
    end note

    note bottom of UnsubscribeStatus
        ・ログイン制限中は退会済みに更新できない
        ・本登録済みステータスが未登録の場合は、退会済みに更新できない
    end note

    AuthenticationAccount *-down- UserId
    AuthenticationAccount *-down- UserEmail
    AuthenticationAccount *-down- UserPassword
    AuthenticationAccount *-down- DefinitiveRegistrationCompletedStatus
    AuthenticationAccount *-down- LoginRestriction
    AuthenticationAccount *-down- UnsubscribeStatus

    LoginRestriction *-down- FailedLoginCount
    LoginRestriction *-down- LoginRestrictionStatus
    LoginRestriction *-down- NextLoginAllowedAt
}

@enduml