@startuml userRegister
title ユーザー登録
hide footbox

Actor User
participant "認証システム" as authSystem
participant DB 

== ユーザー登録 ==
User -> authSystem : メールアドレスとパスワードを入力
activate authSystem
authSystem -> authSystem : バリデーション
authSystem -> DB : メールアドレスとパスワードを保存
authSystem <- DB
authSystem -> DB : ワンタイムトークンとトークンの有効期限、ワンタイムパスワードを保存
authSystem <- DB
User <- authSystem : 本登録済み更新URLとワンタイムパスワードをメール送信する\n（本登録済み更新URLのクエリパラメータにはワンタイムトークンが設定されている）
deactivate authSystem

== 本登録済み更新処理 ==
User -> authSystem : 本登録済み更新URLにアクセス
activate authSystem
authSystem -> authSystem : ワンタイムトークンが存在するかどうか・トークンの有効期限をバリデーション
User <- authSystem : ワンタイムトークン入力画面
User -> authSystem : ワンタイムトークンを入力
authSystem -> authSystem : 正しいワンタイムトークンかどうか・正しいワンタイムパスワードかどうか・トークンの有効期限を判定
authSystem -> DB : ユーザーの認証アカウントを「本登録済み」に更新
authSystem <- DB
authSystem -> DB : ワンタイムトークン情報を削除
deactivate authSystem

== ワンタイムトークンの期限が切れている場合 ==
User -> authSystem : 本登録済み更新URLにアクセス
activate authSystem
authSystem -> authSystem : ワンタイムトークンが存在するかどうか・トークンの有効期限をバリデーション
User <- authSystem : ワンタイムトークン再発行画面をレスポンス
User -> authSystem : ワンタイムトークン再発行
authSystem -> DB : 新しいワンタイムトークン情報を更新する
authSystem <- DB
User <- authSystem : 新たな本登録済み更新URLとワンタイムパスワードをメール送信する\n（本登録済み更新URLのクエリパラメータにはワンタイムトークンが設定されている）
deactivate authSystem

@enduml